using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NFTB.Contracts.Entities.Lists {
	
	/// <summary>
	/// 
	/// Originally generated by scaffolding code
	/// </summary>
	public partial class SystemLogList{
	
	
	}
}

